# SpringBoot整合Mybatis相关配置



name: sangeng
age: 15
date: 2005/1/1


#student:
#  name: sangeng
#  age: 15

map:
  k1: v1
  k2: v2

student2: {name: sangeng,age: 15}


list:
  - sang
  - geng
  - cao
  - tang

students:
  - name: sangeng
    age: 17
  - name: caotang
    age: 14
  - {name: sangeng,age: 15}

server:
  port: ${myPort:88}
myPort: 80


# 练习
student:
  lastName: sangeng
  age: 15
  boss: true
  birthday: 2006/2/3
  maps:
    name: sangeng
    age: 11
  maps2: {name: caotang,age: 199}
  list:
    - name: 小白
      age: 3
    - name: 小黄
      age: 4
    - {name: 小黑,age: 1}
  dog:
    name: 小红
    age: 5
  arr:
    - sangeng
    - caotang

  arr2: [sangeng,caotang]
  dogMap:
    xb: {name: 小白,age: 9}
    xh:
      name: 小红
      age: 6

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot_test?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml # mapper映射文件路径
  type-aliases-package: com.sangeng.domain   # 配置哪个包下的类有默认的别名
